### ISSUE TITLE
Extend the AEM scripts to detect TPM version on the platform

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#14]
**Is your feature request related to a problem? Please describe.**

Currently, Qubes OS AEM fully supports TPM 1.2 but has no support for TPM 2.0. This issue is required to extend the AEM scripts to detect the TPM version on the platform and use the appropriate software stack for the given TPM.

**Is your feature request related to a new idea or technology that
would benefit the project? Please describe.**

This task is required to extend Qubes OS AEM to support TPM 2.0 on Intel hardware.

**Describe the solution you'd like**

Extend the AEM scripts to detect the TPM version on the platform and use the appropriate software stack for the given TPM. This issue implements the AEM TPM 1.2 equivalent functionalities using TPM 2.0 software stack and as a result allowing the use of TPM 2.0 with Qubes OS AEM. It will require implementing the access to TPM 2.0 NVRAM, sealing and unsealing the secret data and generating TOTP.

**Describe alternatives you've considered**

N/A

**Additional context**

This feature request is part of Phase 2 in TrenchBoot as Anti Evil Maid project, as outlined in the documentation: https://docs.dasharo.com/projects/trenchboot-aem-v2/.

**Relevant documentation you've consulted**

N/A

**Comment by SergiiDmytruk** [comment]
@miczyg1, should [`90anti-evil-maid/anti-evil-maid-unseal`](https://github.com/QubesOS/qubes-antievilmaid/blob/main/90anti-evil-maid/anti-evil-maid-unseal) be updated as well?

**Comment by miczyg1** [comment]
I guess so. We don't want any AEM script to touch TPM2.0 without proper support for it.

**Comment by SergiiDmytruk** [comment]
Added a couple commits to https://github.com/QubesOS/qubes-antievilmaid/pull/42 PR.

**Comment by krystian-hebel** [comment]
Other than `bad_pcrs` check for PCR19 I think this should be testable before actual TPM2.0 implementation in Xen. It won't do measurements for TPM2.0 yet, but both PCR17 and PCR18 are extended by ACM. PCR19 may stay at all 00s, not sure what is expected to be measured to this PCR and by whom.

**Comment by macpijan** [comment]
@miczyg1 I guess you could take a look at this then?

I asked Marek about the workflow we should apply also in the future (https://github.com/QubesOS/qubes-antievilmaid/pull/45#issuecomment-1569732519), but this answer should not block the review/test of this code.

**Comment by miczyg1** [comment]
Reviewed https://github.com/QubesOS/qubes-antievilmaid/pull/45

https://github.com/QubesOS/qubes-antievilmaid/pull/42 seems to be a container for all changes (for testing purposes?). Don't know if I should touch it yet and what readiness it has

**Comment by macpijan** [comment]
My understanding was that you should wait for green light from @SergiiDmytruk for a separate PR per each task.
So far, we have only for the one task, and the rest of the two are still in progress.

**Comment by miczyg1** [comment]
I assumed 45 is ready

**Comment by macpijan** [comment]
All comments in: https://github.com/QubesOS/qubes-antievilmaid/pull/45 are resolved
