### ISSUE TITLE
Set up testing infrastructure

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#26]
**Affected component(s) or functionality (if applicable)**
This issue outlines the tasks needed to set up and improve the testing infrastructure

**Brief summary**
_A clear and concise summary of the task that should be done._
Prepare a transparent testing infrastructure with public test results. Prepare a transparent testing infrastructure with public test results. Provide documentation to facilitate the development of TrenchBoot-related components with a list of Intel and AMD devices on which to test the created patches.

- [x] Organize Yocto Meta-TrenchBoot Layer: remove unnecessary metadata from the layer
- [x] Upgrade to the latest Yocto LTS Scarthgap release
- [ ] Migrate the meta-trenchboot layer to the TrenchBoot repository
- [x] Prepare and provide public Yocto build cache
- [x] Prepare repository for publishing test results

**Comment by macpijan** [comment]
Build cache available here: https://cache.dasharo.com/yocto/trenchboot/
Initial version after cleanup has been merged: https://github.com/3mdeb/meta-trenchboot
Still working on documentation, and having a successful boot on hardware - likely some changes on the components' side are required here.

**Comment by BeataZdunczyk** [comment]
>  Prepare repository for publishing test results

The repository for publishing test results is available here: https://github.com/TrenchBoot/test-results

**Comment by BeataZdunczyk** [comment]
> Migrate the meta-trenchboot layer to the TrenchBoot repository

@artur-rs Are you planning to migrate the meta-trenchboot layer to the TrenchBoot repository, or does this issue need updating?

**Comment by artur-rs** [comment]
Yes, after resolving all open PRs related to this phase

**Comment by macpijan** [comment]
> Migrate the meta-trenchboot layer to the TrenchBoot repository

We have decided to move the meta-trenchboot to zarhus organization instead. Most developers of this repo is there, not in the trenchboot organization, where adding new ones is troublesome. This will be more efficient from development perspective.

**Comment by artur-rs** [comment]
`meta-trenchboot` repository has been migrated to Zarhus org: https://github.com/zarhus/meta-trenchboot
Also, opened small changes regarding URL change/pre-commit config: https://github.com/zarhus/meta-trenchboot/pull/51
