### ISSUE TITLE
Rebase existing GRUB code

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#30]
**Affected component(s) or functionality (if applicable)**
_If applicable, the component or functionality of TrenchBoot that this task
concerns._

**Brief summary**
_A clear and concise summary of the task that should be done._

 Refreshing existing GRUB code and implementing necessary fixes for the most up-to-date TrenchBoot boot protocol. This also includes changes to code style to make it compatible with GRUB's expectations. The code will be pushed to the TrenchBoot GRUB repository to serve as a foundation for future TrenchBoot activities.

**Comment by SergiiDmytruk** [comment]
Diff between current GRUB2's master and rebased code (`tb-2.12-57` branch) can be seen there: https://github.com/TrenchBoot/grub/compare/b53ec06a1...tb-2.12-57

P.S. The issue closed due to a label, didn't expect that.
