### ISSUE TITLE
Update SKL for SL specification and push changes to SKL repository

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#33]
**Brief summary**
_A clear and concise summary of the task that should be done._

The existing AMD support was designed and implemented before the Secure Launch (SL) specification was defined. Therefore, changes are required in SKL to use the structures expected by the SL specification. These changes will align SKL with the SL structures and be pushed to the SKL repository.

**Comment by BeataZdunczyk** [comment]
Working on this issue here: https://github.com/TrenchBoot/secure-kernel-loader/pull/21

**Comment by SergiiDmytruk** [comment]
The PR has been merged.
