### ISSUE TITLE
Document AMD DRTM support in Linux kernel

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#35]
**Brief summary**
_A clear and concise summary of the task that should be done._

The task aims to fill the gap in Linux kernel documentation for AMD DRTM technology, that will be sent along with patches implementing AMD DRTM support in Linux kernel.

**Comment by SergiiDmytruk** [comment]
PR: https://github.com/TrenchBoot/linux/pull/124
