### ISSUE TITLE
Send initial patches to GRUB and Linux kernel mailing lists

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#37]
**Brief summary**

First set of messages to both projects' mailing lists should be sent concurrently in order to allow maintainers to test the solution as a whole. This includes any necessary rebasing, patch preparation, and initial communication with maintainers.

**Comment by SergiiDmytruk** [comment]
Sent https://github.com/TrenchBoot/grub/compare/b53ec06...tb-2.12-57-v1 to [grub-devel](https://lists.gnu.org/archive/html/grub-devel/2024-08/msg00088.html) even though AMD patches for Linux aren't ready yet.  That's actually a very small part of the changes and an unlikely reason for stalling the review in any way which needs to move forward by about 4800 lines before reaching AMD part and reviewers are highly likely to take their time.

**Comment by SergiiDmytruk** [comment]
GRUB TXT v3 (AMD part was extracted out of it, but this serves it for a base):
 - ML: https://lists.gnu.org/archive/html/grub-devel/2024-12/msg00028.html
 - Google Groups: https://groups.google.com/g/trenchboot-devel/c/xQs956Hja3c
 - GitHub: https://github.com/TrenchBoot/grub/compare/f6e2ef2...tb-2.12-139-v3

GRUB AMD (RFC):
 - ML: https://lists.gnu.org/archive/html/grub-devel/2024-12/msg00095.html
 - Google Groups: https://groups.google.com/g/trenchboot-devel/c/Tr8E6GK-NmA
 - GitHub: https://github.com/TrenchBoot/grub/compare/tb-2.12-139-v3...tb-amd-2.12-139-rfc-v1

Linux AMD (RFC):
 - ML: https://lore.kernel.org/lkml/cover.1734008878.git.sergii.dmytruk@3mdeb.com/
 - Google Groups: https://groups.google.com/g/trenchboot-devel/c/m36mOzNnqfY
 - GitHub: https://github.com/TrenchBoot/linux/compare/linux-sl-master-9-12-24-v11...linux-sl-master-amd-rfc-v1
