### ISSUE TITLE
TrenchBoot support for UEFI boot mode in Xen for Intel and AMD hardware

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#40]
**Brief summary**
_A clear and concise summary of the task that should be done._
This task focuses on expanding TrenchBoot support for UEFI boot mode with DRTM in Xen , targeting both Intel and AMD hardware.
This task includes implementing support for the most recent TrenchBoot boot protocol in the Xen hypervisor for Intel and AMD platforms running UEFI compliant firmware.

**Comment by krystian-hebel** [comment]
Updates to both implementation and specification have been merged, see linked PRs above.

**Comment by ghost** [comment]
Does this mean TrenchBoot can be used as the AEM implementation on a Qubes system running UEFI now?

**Comment by krystian-hebel** [comment]
Not yet, this is just Xen part, some changes are still to be done on GRUB side.
