### ISSUE TITLE
Fix "Build and push Docker image" workflow

### ISSUE THREAD

**Issue by artur-rs** [TrenchBoot/trenchboot-issues#51]
**Affected component(s) or functionality**

tenchboot-sdk: https://github.com/TrenchBoot/trenchboot-sdk

**Brief summary**

During the work with pre-commit setup, another CI workflow returns error:
https://github.com/TrenchBoot/trenchboot-sdk/actions/runs/10945946130/job/30391293792?pr=10

**Version**

All?

**To Reproduce**

Run CI workflow from the GH Actions: https://github.com/TrenchBoot/trenchboot-sdk/actions/workflows/main.yml

**Expected behavior**

CI workflow "Build and push Docker image" should end with a success.

**Actual behavior**

```
Error: buildx call failed with: ERROR: failed to solve: process "/bin/sh -c useradd -p locked -m trenchboot && \tapt-get -qq update && \tapt-get -qqy install \t\tautoconf \t\tautopoint \t\tbcc \t\tbin86 \t\tbison \t\tbridge-utils \t\tbsdextrautils \t\tbuild-essential \t\tbzip2 \t\tccache \t\te2fslibs-dev \t\tflex \t\tflex \t\tgawk \t\tgcc \t\tgettext \t\tgit \t\tgit-core \t\tiasl \t\tiproute2 \t\tlibaio-dev \t\tlibbz2-dev \t\tlibc6-dev \t\tlibc6-dev-i386 \t\tlibcurl4 \t\tlibcurl4-openssl-dev \t\tliblzma-dev \t\tlibncurses5-dev \t\tlibpci-dev \t\tlibpixman-1-dev \t\tlibsdl-dev \t\tlibsystemd-dev \t\tlibvncserver-dev \t\tlibx11-dev \t\tlibyajl-dev \t\tmake \t\tmarkdown \t\tmercurial \t\tmeson \t\tocaml \t\tocaml-findlib \t\tpandoc \t\tpatch \t\tpkg-config \t\tpython \t\tpython \t\tpython-dev \t\tpython3-dev \t\ttexinfo \t\ttexlive-fonts-extra \t\ttexlive-fonts-recommended \t\ttexlive-latex-base \t\ttexlive-latex-recommended \t\ttgif \t\ttransfig \t\tuuid-dev \t\twget \t\txz-utils \t\tzlib1g-dev \t&& apt-get clean" did not complete successfully: exit code: 100
```

**Screenshots**
**Additional context**
**Solutions you've tried**
**Relevant documentation you've consulted**
**Related, non-duplicate issues**

**Comment by krystian-hebel** [comment]
https://github.com/TrenchBoot/trenchboot-sdk/pull/12 should fix this, I'm waiting for CI to build the container after a rebase to confirm it still works. Ideally it should be based on something else than `stable`.

**Comment by krystian-hebel** [comment]
It works, for now.
